"""Subprocess execution for generated code.

Important: this is a CORRECTNESS sandbox, not a security sandbox. The
code is generated by our own LLM and runs in our own environment. The
limits below — timeout, empty cwd, env={}, closed stdin — keep the
generated code from accidentally interacting with AEDOS state or
hanging. They do NOT prevent a determined attacker from doing weird
things; that isn't the threat model here.

If the code-writing model produces a script that imports a network
library or writes to disk, the comparator will see surprising stdout
and surface a comparison_error. We log unusual behavior (stderr output,
slow runs) but don't try to prevent it.
"""

from __future__ import annotations

import os
import subprocess
import sys
import tempfile
import time
from dataclasses import dataclass
from typing import Any


_DEFAULT_TIMEOUT_SECONDS = 5
_SLOW_RUN_THRESHOLD_MS = 1000


@dataclass
class ExecutionResult:
    success: bool
    stdout: str
    stderr: str
    exit_code: int
    duration_ms: int
    timed_out: bool
    error: str | None = None  # set on infrastructure failures (couldn't even spawn)

    @property
    def slow(self) -> bool:
        return self.duration_ms >= _SLOW_RUN_THRESHOLD_MS

    def to_dict(self) -> dict[str, Any]:
        return {
            "success": self.success,
            "stdout": self.stdout,
            "stderr": self.stderr,
            "exit_code": self.exit_code,
            "duration_ms": self.duration_ms,
            "timed_out": self.timed_out,
            "error": self.error,
            "slow": self.slow,
        }


def run_code(code: str, *, timeout_seconds: int = _DEFAULT_TIMEOUT_SECONDS) -> ExecutionResult:
    """Run ``code`` in a subprocess with strict limits.

    The subprocess uses ``sys.executable``, has stdin closed, runs in an
    empty temporary directory, and inherits no environment variables.
    """
    started = time.monotonic()
    with tempfile.TemporaryDirectory() as workdir:
        # On Windows, env={} can be problematic for subprocess startup
        # (it needs SYSTEMROOT to load DLLs). Pass a minimal env that's
        # enough for python to start but exposes no AEDOS state.
        minimal_env: dict[str, str] = {}
        if sys.platform == "win32":
            for k in ("SYSTEMROOT", "PATH", "PATHEXT", "TEMP", "TMP"):
                if k in os.environ:
                    minimal_env[k] = os.environ[k]

        try:
            completed = subprocess.run(
                [sys.executable, "-c", code],
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                cwd=workdir,
                env=minimal_env,
                timeout=timeout_seconds,
                text=True,
            )
        except subprocess.TimeoutExpired as e:
            elapsed_ms = int((time.monotonic() - started) * 1000)
            return ExecutionResult(
                success=False,
                stdout=(e.stdout or "") if isinstance(e.stdout, str) else "",
                stderr=(e.stderr or "") if isinstance(e.stderr, str) else "",
                exit_code=-1,
                duration_ms=elapsed_ms,
                timed_out=True,
                error=f"timed out after {timeout_seconds}s",
            )
        except (OSError, ValueError) as e:
            elapsed_ms = int((time.monotonic() - started) * 1000)
            return ExecutionResult(
                success=False,
                stdout="",
                stderr="",
                exit_code=-1,
                duration_ms=elapsed_ms,
                timed_out=False,
                error=f"{type(e).__name__}: {e}",
            )

    elapsed_ms = int((time.monotonic() - started) * 1000)
    return ExecutionResult(
        success=completed.returncode == 0,
        stdout=completed.stdout or "",
        stderr=completed.stderr or "",
        exit_code=int(completed.returncode),
        duration_ms=elapsed_ms,
        timed_out=False,
    )
